name: CI

on:
  workflow_dispatch:

  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Run build
        run: pnpm run build
        shell: bash

      - name: Run test preparation
        run: pnpm run test:prepare
        shell: bash

      - name: Run tests
        run: pnpm run test
        shell: bash

  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Run linter
        run: pnpm run lint
        shell: bash

  typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare workflow
        uses: ./.github/actions/prepare-workflow

      - name: Run typecheck
        run: pnpm run typecheck
        shell: bash
