# name: Create release and publish to NPM Registry

# on:
#   push:
#     branches:
#       - master

# jobs:
#   release-please:
#     permissions:
#       contents: write
#       pull-requests: write

#     runs-on: ubuntu-latest
#     steps:
#       - uses: googleapis/release-please-action@v4
#         id: release
#         with:
#           config-file: release-please-config.json
#           token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
